export {
  GenerarCuotasDto,
  RegistrarPagoDto,
  RegistrarPagoMultipleDto,
  CuentaCorrienteQueryDto,
  ReporteCobranzaQueryDto,
  TalonarioQueryDto,
  TarjetaCentroArchivoQueryDto,
  SocioElegibleDto,
  SociosElegiblesResponseDto,
  GenerarCuotasSeleccionDto,
  GenerarCuotasSeleccionResponseDto,
  EstadoPagosQueryDto,
  SocioPagosAnualDto,
  EstadoPagosResponseDto,
  CuotasQueryDto,
  // Morosos detallados
  SeveridadMoroso,
  MorososQueryDto,
  UltimoPagoDto,
  CategoriaMorosoDto,
  MorosoDetalladoDto,
  MorososStatsDto,
  MorososDetalladosResponseDto,
  // Reporte por rango
  ReporteCobranzaRangoQueryDto,
  ReporteCobranzaMesDto,
  ReporteCobranzaRangoResponseDto,
} from './cobros.dto';
