export {
  GenerarCuotasDto,
  RegistrarPagoDto,
  RegistrarPagoMultipleDto,
  RegistrarOperacionCobroDto,
  ConceptoCobroDto,
  MisCobranzasRangoDto,
  RegistrarPagoCuotasSeleccionadasDto,
  ReciboMultipleCuotasDto,
  PagoMetodoMontoDto,
  CuentaCorrienteQueryDto,
  ReporteCobranzaQueryDto,
  TalonarioQueryDto,
  TarjetaCentroArchivoQueryDto,
  TarjetaCentroResultadoDto,
  ProcesarResultadosTarjetaCentroDto,
  SocioElegibleDto,
  SociosElegiblesResponseDto,
  GenerarCuotasSeleccionDto,
  GenerarCuotasSeleccionResponseDto,
  EstadoPagosQueryDto,
  SocioPagosAnualDto,
  EstadoPagosResponseDto,
  CuotasQueryDto,
  // Morosos detallados
  SeveridadMoroso,
  MorososQueryDto,
  UltimoPagoDto,
  CategoriaMorosoDto,
  MorosoDetalladoDto,
  MorososStatsDto,
  MorososDetalladosResponseDto,
  // Reporte por rango
  ReporteCobranzaRangoQueryDto,
  ReporteCobranzaMesDto,
  ReporteCobranzaRangoResponseDto,
} from './cobros.dto';
export { CobroSocioDto, RegistrarCobroGrupalDto } from './registrar-cobro-grupal.dto';
